### ISSUE TITLE
Interest triggered popovers should be hidden when dialogs are opened

### ISSUE THREAD

**Issue by lukewarlow** [keithamus/invoker-buttons-proposal#17]
Load the demo page hover the "This will open the dialog button". A popover is shown, now click the button a dialog opens. Now if you close the dialog the popover will still be open.

If this is just a bug with the demo fair enough. If this is intentional I think it should be changed.

**Comment by keithamus** [comment]
This may be a bug in Chrome, I believe opening a dialog should close all `auto` popovers.

**Comment by lukewarlow** [comment]
Having said that it does seem to be the demo that's doing something odd because I can't reproduce in a minimal fashion. I'm wondering if it's invoking and then reshowing the popover in a new interest event. And potentially Safari handles *something* different

**Comment by mfreed7** [comment]
Modal dialogs should absolutely close popover=auto's. If you're finding that they don't, and you can minimize it, please do file a bug.

**Comment by lukewarlow** [comment]
Did some digging on this and it seems like Chrome is working as expected. The interest is just re-triggering making it look like it's broken.
