### ISSUE TITLE
Should this proposal move over to an OpenUI explainer/proposal?

### ISSUE THREAD

**Issue by mfreed7** [keithamus/invoker-buttons-proposal#29]
Feels like yes, but up to you.

**Comment by keithamus** [comment]
Happy to do so - how should we do that? Move the markdown over in a git commit and transfer all issues?

**Comment by mfreed7** [comment]
> Happy to do so - how should we do that? Move the markdown over in a git commit and transfer all issues?

Great! Thanks. For the explainer, yes I think just put up a PR with the entire content of the markdown. I'm happy to review that.

As for issues, that's a bit more difficult, at least for me. But as I'm typing this, I realize you're more likely than anyone I know to invoke the proper Github magic to migrate the issues. So I'll leave that to you!

**Comment by YummyBacon5** [comment]
Since this has now moved, this should probably be mentioned in the [README.md](https://github.com/keithamus/invoker-buttons-proposal/blob/main/README.md).
