### ISSUE TITLE
Add `<select>` opening as a default behaviour?

### ISSUE THREAD

**Issue by lukewarlow** [keithamus/invoker-buttons-proposal#9]
While there's currently no JS equivalent to open a select element, I've made https://github.com/whatwg/html/pull/9754 which would add a `showPicker()` function to select elements.
It would make sense for an auto invoker action on selects to trigger this behaviour.

Much like for inputs (in my [PR](https://github.com/keithamus/invoker-buttons-proposal/pull/7) to this repo), and I imagine for `<selectlist>` once that proposal is in HTML.

**Comment by keithamus** [comment]
I think there will be work to align with the new [`<selectlist>` element](https://open-ui.org/components/selectlist/). Right now that spec includes new `type=` values but perhaps we should discuss what it would look like to leverage `invokertarget` instead.

**Comment by lukewarlow** [comment]
Yeah I think `<selectlist>` probably needs more of a discussion. `<select>` should hopefully be simple enough once that proposal is accepted.

**Comment by keithamus** [comment]
Perhaps regardless of `showPicker` on `<select>` having traction, this is a useful addition for `<select>`. So I'm :+1: on this. PRs welcome :smile:
